### ISSUE TITLE
CAIRN and TRAVIS

### ISSUE THREAD

**Issue by AGCooper** [ezpaarse-project/ezpaarse-platforms#129]
Travis is throwing an error on pull requests that it probably should not.

```1 failing

    CAIRN works:
    Uncaught TypeError: match[3].padEnd is not a function
    at analyseEC [as analyse] (/home/travis/build/ezpaarse-project/ezpaarse-platforms/cairn/parser.js:108:40)
    at Parser.execute (parser.js:70:19)
    at test/platforms-test.js:50:37
    at convertFile (test/platforms-test.js:81:27)
    at test/platforms-test.js:109:9
    at Converter. (node_modules/csvtojson/libs/core/Converter.js:567:9)
    at Converter.flushCb (node_modules/csvtojson/libs/core/Converter.js:448:10)
    at Converter.checkAndFlush (node_modules/csvtojson/libs/core/Converter.js:483:10)
    at Converter. (node_modules/csvtojson/libs/core/Converter.js:463:12)
    at Converter.processData (node_modules/csvtojson/libs/core/Converter.js:191:9)
    at Converter._flush (node_modules/csvtojson/libs/core/Converter.js:462:10)
    at Converter. (_stream_transform.js:118:12)
    at prefinish (_stream_writable.js:458:12)
    at finishMaybe (_stream_writable.js:466:7)
    at endWritable (_stream_writable.js:478:3)
    at Converter.Writable.end (_stream_writable.js:443:5)
    at ReadStream.onend (_stream_readable.js:490:10)
    at endReadableNT (_stream_readable.js:905:12)
```

When I run make test cairn (an older version) I get no errors.

**Comment by nojhamster** [comment]
Thanks for the report, this has been fixed in f2f3e3bf3a9bb39ab37f3d3a700c4f0d2b2763c3
